language: objective-c
os: osx
osx_image:
  - xcode11.3
  - xcode11.2
  - xcode10.3
env:
  - TOOLCHAIN=bazel
  - PROJECT="MDFInternationalization"
  - PROJECT="Examples/Flags"
jobs:
  include:
    # We only need to run pod lib lint once and with the latest Xcode version.
    - name: "pod lib lint"
      osx_image: xcode11.3
      env: TOOLCHAIN=cocoapods
before_install:
  - if [ "$TOOLCHAIN" == "bazel" ]; then
      wget -O bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.2.1/bazelisk-darwin-amd64";
      chmod +x "bazelisk";
    fi
script:
  - if [ "$TOOLCHAIN" == "bazel" ]; then
      ./bazelisk test //...;
    elif [ "$TOOLCHAIN" == "cocoapods" ]; then
      pod lib lint;
    elif [ "$PROJECT" == "MDFInternationalization" ]; then
      set -o pipefail;
      xcodebuild build
        -project MDFInternationalization.xcodeproj
        -scheme MDFInternationalization
        -destination "platform=iOS Simulator,name=iPhone Xs Max,OS=12.2" | xcpretty;
    elif [ "$PROJECT" == "Examples/Flags" ]; then
      set -o pipefail;
      xcodebuild build
        -workspace Examples/Flags.xcworkspace
        -scheme Flags
        -destination "platform=iOS Simulator,name=iPhone Xs Max,OS=12.2" | xcpretty;
    fi
